name: 'Publish release'
description: 'Publish a release and update the release notes'
inputs:
  version:
    description: 'Release version'
    required: true
  id:
    description: 'Release ID'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
