language: minimal

branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - .travis/build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist

